### ISSUE TITLE
Introduce skill system

### ISSUE THREAD

**Issue by yehric2018** [yehric2018/mmobot#15]
Skills will allow players to differentiate from each other by giving them skills at certain things. Throughout a day, a player can gain up to 2 skill points that they can expend on a certain skill, which will improve their proficiency in that skill. The skills we aim to support for now are:

- Fighter (fighting): Hand to hand combat
- Archer/Marksman (marksmanship): Using a bow and arrow
- Blacksmith (smithing): Craft metal objects
- Farmer (farming): Tend to animals
- Weaver (weaving): Craft attire
- Carpenter (carpentry): Construct wooden objects
- Mason (masonry): Craft stone objects
- Apothecary (medicine): Craft and apply medicine and remedies
- Cook/Baker (cooking): Make food
- Fisher (fishing): Hunting fish and other marine life

Within each of these skills, there are subskills that can be learned that have special properties that affect vocations. For example, sword skills can be leveled up within the fighting category.

## Design
We already have a table called PlayerStats that lists out stats, which contains fighting skills, crafting skills, etc. which are not currently being used. We will remove these columns from the PlayerStats table, and move them to a new table called PlayerSkills. This table will have a one-to-one mapping with the Players table, and will highlight the level of each skill the player has. We will also have a column in this table including the number of skill points to be allocated.

For gaining skill points, we will increment the skill_points by 2 every day for now (this is prone to change). We will make such changes to the event bot via a 12-hour timer.

## Milestones

- [x] Introduce the PlayerSkills table that includes fields for all the skills we intend to introduce, as well as field for skill_points, last_learned, and last_taught
- [x] Introduce SkillTeaching table that includes metadata and taught skills. The fields in this table will include teaching_time, skill, teacher, learner.
- [x] Remove skill-related fields from PlayerStats
- [x] Attach PlayerSkills to the Player model
- [x] Add a 12-hour event to the events bot that increments the skill_points field by 1
- [ ] Introduce learn command, which decrements the skill_points field and increments another skill field by 1 if not maxed. If the leveled up skill is present in the SkillTeachings table, the skill_points field is not decremented, and instead we just set the last_learned field to the present time and clear all learned skills during the time.
- [ ] Introduce teach command, which sets the last_taught field to the current time. This adds an entry to the SkillTeaching table, which later the learner can use to level up a skill. The teach command does not work if the last_taught time was less than 4 hours ago. The teach command also only works if your skill level in that trade is at least 5 greater than the learner.
- [ ] Write tests for the learn and teach commands, then attach to the main bot

**Comment by yehric2018** [comment]
We will likely continue to add on new skills: not just for each occupation, but also subskills within each category. Therefore, it is not very scalable to have each skill correspond to a single field in the PlayerSkills table. It would be better to create a row for each player-skill pair, which would also give information on the level of the skills.

Here is the revised roadmap for implementing PlayerSkills:

- [ ] Get rid of the skills_id field from Players
- [ ] Replace the PlayerSkills table with a new table with the following fields: player_id, skill_name, skill_level
- [ ] Add a relationship in the Players table so we can retrieve all the learned skills for a given Player.
- [ ] Move the skill_points field to PlayerStats
- [ ] Revise the events_bot to modify skill_points from PlayerStats instead of from PlayerSkills
- [ ] Revise the teach command to utilize the revise SkillPoints model
- [ ] Introduce the learn command
- [ ] Write tests for learn and teach, then attach to the main bot
