### ISSUE TITLE
Allow a player to be incapacitated and killed

### ISSUE THREAD

**Issue by yehric2018** [yehric2018/mmobot#16]
Perma-death has always been one of the main features of the MMO, so we are going to implement perma-death.

Incapacitation is a state where you are still alive, but you cannot do anything. This prevents you from performing any commands, but you can still speak. You become incapacitated if your HP hits 0 or below.

When you are incapacitated, the only way to be revived is by using an item with revitalizing effects on you. Otherwise, this is more of just a state for you to say goodbye to the world before moving to the afterlife.

Death happens after incapacitation. There are two ways to die after being incapacitated.
- You are attacked after being incapacitated.
- 2 minutes passes after being incapacitated.

After death, you can no longer read messages in the world channels, and you will gain access to the #afterlife channel, where you can talk to fellow adventurers who have also passed recently. You lose access to the #afterlife channel when you create a new account.

## TODO:

- [x] When a player is attacked and their HP goes below 0, incapacitate them
- [x] For the scheduled jobs that decrement HP, incapacitate any player whose HP goes below 0
- [ ] Add checks to every command to ensure the player cannot do any useful commands once incapacitated.
- [x] Create the event that gets run to effectively kill the player, which will set is_active to false and move them from the world channel they are currently in to the afterlife channel.
- [ ] Test to ensure that the events are successfully incapacitating the players.
- [ ] When a player is incapacitated from hunger, we need to announce that they were incapacitated in their current Discord channel.
- [ ] When a player is attacked while incapacitated, we instantly trigger the kill_player job
- [ ] Do a scan of incapacitated players upon bot start-up: We will be nice to these people and reset them to 1 HP

**Comment by yehric2018** [comment]
We were originally going to introduce the hunger and thirst stats here, however to simplify things, we decided to instead combine these stats with HP and endurance. Now instead of recovering HP over time, your HP will decrease over time to show you getting hungry over time. Endurance will be incremented, but very slowly. This will encourage players to eat food that will increase their HP and endurance.

**Comment by yehric2018** [comment]
The process of killing players is very clunky, especially since we need to do several things on the client side such as sending messages in the channel where the player was incapacitated/killed, which is not always readily available (especially within the scheduled decrement HP event). It would be good to find ways to factor out much of the logic and reduce computation/complexity.

**Comment by yehric2018** [comment]
Much of the design for incapacitation and killing was changed over time, so the original prompt is not so relevant anymore. The main change is that we shifted away from using APScheduler and instead towards using asyncio library.

The main motivation away from using APScheduler is that it runs it's jobs separate from the Discord bot itself. This requires to pass lots of arguments over to the scheduled job, all of which need to be serializable. Unfortunately, several necessary arguments such as the Discord client itself and the database engine are not serializable. Therefore, it is much less of hassle to run the jobs inside the bot itself.

Our new design is as follows:
- We will schedule several tasks upfront utilizing discord.tasks, which uses interval-based job scheduling.
- For handling incapacitation, we will now instead call asyncio.sleep before killing the player. I have tested that this still allows us to run and complete other commands while the sleep is happening, so hopefully it will not slow down the execution of the entire bot too much.

With this new design, we will still need to make sure to implement all the requirements for incapacitation and dying to work, along with other tasks:

- [ ] Refactor the code for a more clear flow of logic, especially in the attack function
- [ ] Add scheduled jobs to decrement HP, and to incapacitate players whose HP falls below 0
- [ ] Add checks to every command so dead/incapacitated players cannot perform them
- [ ] Test to ensure that the events are successfully incapacitating the players
- [ ] When a player is incapacitated from hunger, we need to announce that they were in the Discord channel
- [ ] When a player is attacked while incapacitated, we instantly kill them
- [ ] Deprecate events_bot.py
- [ ] Do a scan of incapacitated players upon bot start-up: We will be nice to these people and reset them to 1 HP

**Comment by yehric2018** [comment]
For incapacitation checks, we are going to check two things:
1. Their is_active status is True, otherwise they are dead
2. Their HP is greater than 0, otherwise they are incapacitated
If they are dead and try to run a command, we should log some kind of error, since it shouldn't be possible for them to even send messages when they are dead. If their HP is equal to 0, then we can just return from the command and do nothing - this will have the affect of trying to do something but failing. Another option is to send a more detailed message in the channel or DMs that just states they are incapacitated.

For now, we do not have any error handling for invalid states (something that we should probably add later), so as of now we will just add checks for HP > 0. Following this, we need to add test cases for all the disabled commands to ensure they either don't do anything or send the correct message in the channels.

The disabled commands are as follows:

- [ ] Attack
- [ ] Equip
- [ ] Learn
- [ ] Move
- [ ] Pickup
- [ ] Teach
- [ ] Unequip

**Comment by yehric2018** [comment]
Our main bulk of work here is pretty much complete - two smaller unfinished issues that are more or less optional have been converted to separate issues.

This functionality was definitely trickier and more time-intensive to implement than I expected. However, being able to die in the game is a vital to the experience this MMORPG seeks to offer, so I think the amount of work put into this task is well warranted.
